stages:
  - diff
  - lint
  - test
diff:
  stage: diff
  image:
    name: $CI_REGISTRY_GO/golang:1.19
    entrypoint: [""]
  tags:
    - go
  script:
    - make generate
    - git diff
    - test -z "$(git diff 2> /dev/null)" || exit 'Files are not generated or formatted with gofumpt, issue `make generate` and commit the result'
    - test -z "$(git ls-files --others --exclude-standard 2> /dev/null)" || exit 'Generation created untracked files, cannot proceed'
  only:
    - merge_requests
    - branches
golangci_lint:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/lint:1.50.0
    entrypoint: [""]
  tags:
    - go
  script:
    - golangci-lint run --enable-all
  only:
    - merge_requests
    - branches
lint-commit-msg:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/commit-check:3.0.0
    entrypoint: [""]
  tags:
    - go
  script:
    - /check
  only:
    - merge_requests
tidy:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/golang:1.18
    entrypoint: [""]
  tags:
    - go
  script:
    - go mod tidy
    - test -z "$(git diff 2> /dev/null)" || exit 'Go modules not tidied, issue \`go mod tidy\` and commit the result'
  only:
    - merge_requests
    - branches
test:
  stage: test
  image:
    name: $CI_REGISTRY_GO/golang:1.18
    entrypoint: [""]
  tags:
    - go
  script:
    - go build -v .
    - make test
  only:
    - merge_requests
    - branches
