linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 30
  cyclop:
    max-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable-all: true
  disable:
    - golint # deprecated, replaced with revive
    - interfacer # deprecated
    - maligned # deprecated
    - wrapcheck
    - nlreturn
    - gomnd
    - goerr113
    - exhaustivestruct
    - wsl
    - whitespace
    - lll
    - scopelint
    - nestif
    - funlen
    - paralleltest
    - godot
    - varnamelen
    - ireturn

    - goconst
    - exhaustruct
    - nonamedreturns
    - dupword

run:
  skip-dirs:
    - test

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G[501]"
